version = 1

[merge]
method = "squash"
delete_branch_on_merge = true
optimistic_updates = true
prioritize_ready_to_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
include_coauthors = true

[update]
always = true

[approve]
auto_approve_usernames = ["dependabot[bot]", "renovate[bot]"]
auto_approve_dependency_upgrades_minor = true
auto_approve_dependency_upgrades_patch = true

[checks]
wait_for_checks = true
required_checks = ["Quality Checks & Build"]
