version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "Europe/Athens"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      patch-updates:
        patterns: ["*"]
        update-types: ["patch"]
      minor-updates:
        patterns: ["*"]
        exclude-patterns: ["vite", "knip", "astro*", "@astrojs/*"]
        update-types: ["minor"]
    ignore:
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "knip"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "Europe/Athens"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns: ["*"]
    labels:
      - "dependencies"
