name: Setup Bun and install dependencies
description: Sets up Bun, caches Bun downloads, and installs dependencies with a frozen lockfile
inputs:
  bun-version:
    description: Bun version to install
    required: false
    default: latest
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun downloads
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
