name: Sync Lockfile

on:
  pull_request:
    paths: [package.json]

permissions:
  contents: read

jobs:
  sync:
    permissions:
      contents: write
    uses: dacrab/.github-workflows/.github/workflows/bun-sync-lockfile.yml@v1
    with:
      app-client-id: ${{ vars.BOT_APP_CLIENT_ID }}
    secrets:
      app_private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
