name: Sync Lockfile

on:
  pull_request:
    paths: ["package.json"]

permissions:
  contents: write

jobs:
  sync:
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - run: bun install

      - uses: stefanzweifel/git-auto-commit-action@v7
